language: go

php:
    - 1.2
    - 1.3
    - 1.4
    - 1.5

# faster builds on new travis setup not using sudo
sudo: false

git:
    submodules: false

script:
    - go test -v ./...
    - go test -bench=.